{% set name = "pygments-styles" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygments_styles-{{ version }}.tar.gz
  sha256: 49727d051518ea46cc2d78c329c6985311bf27e1826f524c229a40b32cf00cff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pygments

test:
  imports:
    - pygments_styles
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A curated collection of Pygments styles based on VS Code themes.
  dev_url: https://github.com/lepture/pygments-styles
  home: https://pygments-styles.org/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
